apiVersion: v1
kind: Namespace
metadata:
  name: gabs-langcache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langcache
  namespace: gabs-langcache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: langcache
  template:
    metadata:
      labels:
        app: langcache
    spec:
      containers:
        - name: langcache
          image: gacerioni/gabs-redis-langcache:1.1.0
          ports:
            - containerPort: 7860
          env:
            - name: GRADIO_SERVER_NAME
              value: "0.0.0.0"
            - name: GRADIO_SERVER_PORT
              value: "7860"
          envFrom:
            - secretRef:
                name: langcache-env
          readinessProbe:
            httpGet:
              path: /
              port: 7860
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 7860
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: langcache-svc
  namespace: gabs-langcache
  annotations:
    networking.gke.io/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: langcache
  ports:
    - name: http
      port: 80
      targetPort: 7860